#!/usr/bin/env sh
#
# The shell variable $RENEWED_LINEAGE will point to the config live subdirectory,
# (eg: "/etc/letsencrypt/live/example.com") containing the new certificates and
# keys;
# The shell variable $RENEWED_DOMAINS will contain a space-delimited list
# of renewed certificate domains.
#
# To run without renewing:
#
# RENEWED_LINEAGE=/etc/letsencrypt/live/example.com /etc/letsencrypt/renewal-hooks/deploy/lighthttpd
#
# To obtain the first RENEWED_LINEAGE:
#   export RENEWED_LINEAGE=/etc/letsencrypt/live/$(certbot certificates 2>/dev/null | grep "Certificate Name:" | head -1 | cut -d":" -f2 | xargs)
#
# lighthttpd is the webserver used to serve the Asustor admin pages.
# It is located: /usr/etc/lighttpd
#
# The certificates are in: /share/Configuration/certbot/letsencrypt/live/
# and are copied in a convulated way in /usr/builtin/etc/certificate/
#
# In theory, we should have at least two entries in
#   /usr/builtin/etc/certificate/certificate.json
# and a UUID that points to
#   /usr/builtin/etc/certificate/ssl/{UUID}/
#
function logger() {
  echo "${@}" >&2
  syslog --log 0 --level 0 --user SYSTEM --event "${@}"
}

logger "Running renewal-hooks..."

. /usr/local/AppCentral/cappysan-certbot/.env.install
cd ${APKG_CFG_DIR:-/nonexistent} || exit 1

if test "x${RENEWED_LINEAGE}" == "x"; then
   RENEWED_LINEAGE=/etc/letsencrypt/live/$(certbot certificates 2>/dev/null | grep "Certificate Name:" | head -1 | cut -d":" -f2 | xargs)
   echo RENEWED_LINEAGE=$RENEWED_LINEAGE
fi

if test "x${RENEWED_LINEAGE}" == "x"; then
  logger "Skipping, RENEWED_LINEAGE is not set"
  exit 1
elif test -e ${RENEWED_LINEAGE}/privkey.pem; then
  true
else
  logger "No Let's Encrypt certificate found: ${RENEWED_LINEAGE}"
  exit 1
fi

# We need openssl
export PATH=$PATH:/usr/builtin/bin/

# If issuer is Asustor, then our certificates are not installed
if openssl x509 -noout -text -in  /usr/builtin/etc/certificate/ssl.crt | grep Issuer | grep -q Asustor; then
  logger "Not replacing stock Asustor certificate."
  exit 2
fi
# Compare "${RENEWED_LINEAGE}"/cert.pem and /usr/builtin/etc/certificate/ssl.crt
as_src="$(openssl x509 -noout -text -in "${RENEWED_LINEAGE}"/cert.pem | grep "Subject:" | head -1)"
as_dst="$(openssl x509 -noout -text -in /usr/builtin/etc/certificate/ssl.crt | grep "Subject:" | head -1)"
if test "x${as_src}" != "x${as_dst}"; then
  logger "Let's Encrypt certificate not installed."
  exit 2
fi

cat "${RENEWED_LINEAGE}"/privkey.pem > /usr/builtin/etc/certificate/ssl.key
cat "${RENEWED_LINEAGE}"/cert.pem    > /usr/builtin/etc/certificate/ssl.crt
cat "${RENEWED_LINEAGE}"/chain.pem   > /usr/builtin/etc/certificate/chain.crt
cat /usr/builtin/etc/certificate/ssl.key /usr/builtin/etc/certificate/ssl.crt /usr/builtin/etc/certificate/chain.crt > /usr/builtin/etc/certificate/ssl.pem

chmod 644 /usr/builtin/etc/certificate/ssl.crt /usr/builtin/etc/certificate/chain.crt
chmod 600 /usr/builtin/etc/certificate/ssl.key /usr/builtin/etc/certificate/ssl.pem
chown root:root /usr/builtin/etc/certificate/ssl.*
logger "Let's Encrypt certificate refreshed."

exit 0
