#!/usr/bin/env sh
#
# The shell variable $RENEWED_LINEAGE will point to the config live subdirectory,
# (eg: "/etc/letsencrypt/live/example.com") containing the new certificates and
# keys;
# The shell variable $RENEWED_DOMAINS will contain a space-delimited list
# of renewed certificate domains.
#

. /usr/local/AppCentral/cappysan-certbot/.env.install
cd ${APKG_CFG_DIR:-/nonexistent} || exit 1

if test "x${RENEWED_LINEAGE}" == "x"; then
   RENEWED_LINEAGE=/etc/letsencrypt/live/$(certbot certificates 2>/dev/null | grep "Certificate Name:" | head -1 | cut -d":" -f2 | xargs)
   echo RENEWED_LINEAGE=$RENEWED_LINEAGE
fi

if test "x${RENEWED_LINEAGE}" == "x"; then
  echo "Skipping, RENEWED_LINEAGE is not set" >&2
  exit 1
elif test ! -e "${RENEWED_LINEAGE}"/privkey.pem; then
  echo "Skipping, keys not found in ${RENEWED_LINEAGE} directory" >&2
  exit 1
fi

# We need zip
export PATH=$PATH:/usr/builtin/bin/

rm -f ${APKG_CFG_DIR}/certificates.zip 2>/dev/null
if test -f last_run; then
  zip ${APKG_CFG_DIR}/certificates.zip last_run
fi
(cd "${RENEWED_LINEAGE}" && zip ${APKG_CFG_DIR}/certificates.zip cert.pem chain.pem fullchain.pem privkey.pem)

chown admin:root ${APKG_CFG_DIR}/certificates.zip
chmod 640 ${APKG_CFG_DIR}/certificates.zip

exit 0
