#!/usr/bin/env sh

. /usr/local/AppCentral/cappysan-certbot/.env.install
cd ${APKG_CFG_DIR:-/nonexistent} || exit 1

# We need openssl
export PATH=$PATH:/usr/builtin/bin/

# If issuer is Asustor, then our certificates are not installed
if openssl x509 -noout -text -in  /usr/builtin/etc/certificate/ssl.crt | grep Issuer | grep -q Asustor; then
  exit 1
fi
if openssl x509 -noout -text -in "${RENEWED_LINEAGE}"/cert.pem | grep Issuer | grep -q "Let's Encrypt"; then
  true
else
  exit 1
fi

if test -f /etc/init.d/S41lighttpd; then
  /etc/init.d/S41lighttpd restart
fi
exit 0
